DROP TABLE TEMP_DBMAP_SCHEDULE;
CREATE TABLE TEMP_DBMAP_SCHEDULE
SELECT TripID, Route, `Time`, `STOP_ID`,stop_order,MIDPOINT,UP_DOWN FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num) TripID, IF(`Stop` like 'Load'  ,@stop_order:=0,@stop_order:=@stop_order +1) stop_order,Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%A1'  order by `ID`)f1 , (select STOP_ID, case when STOP_NAME ='Stadium (A)' then 'Stadium' else STOP_NAME end STOP_NAME from S_Stop) s where s.STOP_NAME=f1.Stop
UNION
SELECT  TripID, Route, `Time`, `STOP_ID`,stop_order,MIDPOINT,UP_DOWN FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num) TripID,IF(`Stop` like 'Load'  ,@stop_order:=0,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%A2'  order by `ID`)f2, (select STOP_ID, case when STOP_NAME ='Stadium (A)' then 'Stadium' else STOP_NAME end STOP_NAME from S_Stop) s where s.STOP_NAME=f2.Stop
UNION
SELECT  TripID, Route, `Time`, `STOP_ID`,stop_order,MIDPOINT,UP_DOWN FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num) TripID,IF(`Stop` like 'Load'  ,@stop_order:=0,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%A3'  order by `ID`)f3, (select STOP_ID, case when STOP_NAME ='Stadium (A)' then 'Stadium' else STOP_NAME end STOP_NAME from S_Stop) s where s.STOP_NAME=f3.Stop
UNION
SELECT  TripID, Route, `Time`, `STOP_ID`,stop_order,MIDPOINT,UP_DOWN FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num) TripID, IF(`Stop` like 'Load'  ,@stop_order:=0,@stop_order:=@stop_order +1) stop_order,Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%A4'  order by `ID`)f4, (select STOP_ID, case when STOP_NAME ='Stadium (A)' then 'Stadium' else STOP_NAME end STOP_NAME from S_Stop) s where s.STOP_NAME=f4.Stop
UNION
SELECT  TripID, Route, `Time`, `STOP_ID`,stop_order,MIDPOINT,UP_DOWN FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num) TripID, IF(`Stop` like 'Load'  ,@stop_order:=0,@stop_order:=@stop_order +1) stop_order,Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%A5'  order by `ID`)f5, (select STOP_ID, case when STOP_NAME ='Stadium (A)' then 'Stadium' else STOP_NAME end STOP_NAME from S_Stop) s where s.STOP_NAME=f5.Stop
UNION
SELECT  TripID, Route, `Time`, `STOP_ID`,stop_order,MIDPOINT,UP_DOWN FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num) TripID,IF(`Stop` like 'Load'  ,@stop_order:=0,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%A6'  order by `ID`)f6, (select STOP_ID, case when STOP_NAME ='Stadium (A)' then 'Stadium' else STOP_NAME end STOP_NAME from S_Stop) s where s.STOP_NAME=f6.Stop
UNION
SELECT  TripID, Route, `Time`, `STOP_ID`,stop_order,MIDPOINT,UP_DOWN FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num) TripID, IF(`Stop` like 'Load'  ,@stop_order:=0,@stop_order:=@stop_order +1) stop_order,Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%A7'  order by `ID`)f7, (select STOP_ID, case when STOP_NAME ='Stadium (A)' then 'Stadium' else STOP_NAME end STOP_NAME from S_Stop) s where s.STOP_ID=f7.Stop
UNION

SELECT TRIP_ID,Route,`Time`, `STOP_ID`,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG FROM (SELECT @row_num := IF(`Stop` like 'Fisher Court',@row_num+1,@row_num) TRIP_ID,IF(`Stop` like 'Fisher Court'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, @midpoint_reached:=if( @midpoint_reached <>1, @midpoint_reached:=IF(`Stop` like '3rd & Jordan',1,0), @midpoint_reached:=IF(`Stop` like 'Fisher Court',0,1))  reached, case when `Stop` like 'Jordan & 10th' and @midpoint_reached=1 then @down:=1 when `Stop` like 'Fisher Court' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r  JOIN ( SELECT @midpoint_reached :=0)y JOIN ( SELECT @down :=0)x  where Route like '%B1'  order by `ID`)s1 , (select STOP_ID, case when STOP_NAME ='10th & Jordan' then 'Jordan & 10th' else STOP_NAME end STOP_NAME from S_Stop) s where s.STOP_NAME=s1.Stop
UNION
SELECT TRIP_ID,Route,`Time`, `STOP_ID`,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG FROM (SELECT @row_num := IF(`Stop` like 'Fisher Court',@row_num+1,@row_num) TRIP_ID,IF(`Stop` like 'Fisher Court'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, @midpoint_reached:=if( @midpoint_reached <>1, @midpoint_reached:=IF(`Stop` like '3rd & Jordan',1,0), @midpoint_reached:=IF(`Stop` like 'Fisher Court',0,1))  reached, case when `Stop` like 'Jordan & 10th' and @midpoint_reached=1 then @down:=1 when `Stop` like 'Fisher Court' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @midpoint_reached :=0)y JOIN ( SELECT @down :=0)x  where Route like '%B2'  order by `ID`)s2 , (select STOP_ID, case when STOP_NAME ='10th & Jordan' then 'Jordan & 10th' else STOP_NAME end STOP_NAME from S_Stop)  s where s.STOP_NAME=s2.Stop
UNION
SELECT TRIP_ID,Route,`Time`, `STOP_ID`,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG FROM (SELECT @row_num := IF(`Stop` like 'Fisher Court',@row_num+1,@row_num) TRIP_ID,IF(`Stop` like 'Fisher Court'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, @midpoint_reached:=if( @midpoint_reached <>1, @midpoint_reached:=IF(`Stop` like '3rd & Jordan',1,0), @midpoint_reached:=IF(`Stop` like 'Fisher Court',0,1))  reached, case when `Stop` like 'Jordan & 10th' and @midpoint_reached=1 then @down:=1 when `Stop` like 'Fisher Court' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @midpoint_reached :=0)y JOIN ( SELECT @down :=0)x where Route like '%B3'  order by `ID`)s3 , (select STOP_ID, case when STOP_NAME ='10th & Jordan' then 'Jordan & 10th' else STOP_NAME end STOP_NAME from S_Stop)  s where s.STOP_NAME=s3.Stop
UNION
SELECT TRIP_ID,Route,`Time`, `STOP_ID`,stop_order,`MIDPOINT` ,UP_DOWN as DOWN_FLAG FROM (SELECT @row_num := IF(`Stop` like 'Fisher Court',@row_num+1,@row_num) TRIP_ID,IF(`Stop` like 'Fisher Court'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, @midpoint_reached:=if( @midpoint_reached <>1, @midpoint_reached:=IF(`Stop` like '3rd & Jordan',1,0), @midpoint_reached:=IF(`Stop` like 'Fisher Court',0,1))  reached, case when `Stop` like 'Jordan & 10th' and @midpoint_reached=1 then @down:=1 when `Stop` like 'Fisher Court' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @midpoint_reached :=0)y JOIN ( SELECT @down :=0)x where Route like '%B4'  order by `ID`)s4 , (select STOP_ID, case when STOP_NAME ='10th & Jordan' then 'Jordan & 10th' else STOP_NAME end STOP_NAME from S_Stop)  s where s.STOP_NAME=s4.Stop
UNION
SELECT TRIP_ID,Route,`Time`, `STOP_ID`,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG FROM (SELECT @row_num := IF(`Stop` like 'Fisher Court',@row_num+1,@row_num)TRIP_ID ,IF(`Stop` like 'Fisher Court'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop`,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, @midpoint_reached:=if( @midpoint_reached <>1, @midpoint_reached:=IF(`Stop` like '3rd & Jordan',1,0), @midpoint_reached:=IF(`Stop` like 'Fisher Court',0,1))  reached, case when `Stop` like 'Jordan & 10th' and @midpoint_reached=1 then @down:=1 when `Stop` like 'Fisher Court' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @midpoint_reached :=0)y JOIN ( SELECT @down :=0)x  where Route like '%B5'  order by `ID`)s5 , (select STOP_ID, case when STOP_NAME ='10th & Jordan' then 'Jordan & 10th' else STOP_NAME end STOP_NAME from S_Stop)  s where s.STOP_NAME=s5.Stop
UNION

SELECT TRIP_ID,Route,`Time`, `STOP_ID`,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG FROM (SELECT @row_num := IF(`Stop` like 'Evermann',@row_num+1,@row_num) TRIP_ID,IF(`Stop` like 'Evermann'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop` ,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Evermann' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%E1'  order by `ID`)t1 join (SELECT STOP_ID, case when STOP_NAME  like 'Wilkie' then 'Willkie' when STOP_NAME  like 'Well''s Library' then 'Wells Library' else STOP_NAME end STOP_NAME FROM S_Stop) s on s.STOP_NAME=t1.Stop
UNION
SELECT TRIP_ID,Route,`Time`, `STOP_ID`,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG FROM (SELECT @row_num := IF(`Stop` like 'Evermann',@row_num+1,@row_num) TRIP_ID,IF(`Stop` like 'Evermann'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop` ,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Evermann' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%E2'  order by `ID`)t2 join (SELECT STOP_ID, case when STOP_NAME  like 'Wilkie' then 'Willkie' when STOP_NAME  like 'Well''s Library' then 'Wells Library' else STOP_NAME end STOP_NAME FROM S_Stop) s on s.STOP_NAME=t2.Stop
UNION
SELECT TRIP_ID,Route,`Time`, `STOP_ID`,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG FROM (SELECT @row_num := IF(`Stop` like 'Evermann',@row_num+1,@row_num) TRIP_ID,IF(`Stop` like 'Evermann'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop` ,IF(`Stop` like '3rd & Jordan',1,0) MIDPOINT, case when `Stop` like 'IMU' then @down:=1 when `Stop` like 'Evermann' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%E3'  order by `ID`)t3 join (SELECT STOP_ID, case when STOP_NAME  like 'Wilkie' then 'Willkie' when STOP_NAME  like 'Well''s Library' then 'Wells Library' else STOP_NAME end STOP_NAME FROM S_Stop) s on s.STOP_NAME=t3.Stop
UNION

SELECT TRIP_ID,Route,`Time`, STOP_ID,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG  FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num)TRIP_ID ,IF(`Stop` like 'Load'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop` ,IF(`Stop` like 'IMU',1,0) MIDPOINT, case when `Stop` like 'Stadium ()' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%X1'  order by `ID`)fo3 left join  (SELECT STOP_ID,  case when STOP_NAME  like 'I M U (X)' then 'IMU'  when STOP_NAME  like 'Stadium (x)' then 'Stadium'  else STOP_NAME end STOP_NAME FROM S_Stop where STOP_NAME in ('I M U (X)' ,'Stadium (x)','Stadium ()'))s on  s.STOP_NAME = fo3.Stop
UNION
SELECT TRIP_ID,Route,`Time`, STOP_ID,stop_order,`MIDPOINT`,UP_DOWN as DOWN_FLAG  FROM (SELECT @row_num := IF(`Stop` like 'Load',@row_num+1,@row_num)TRIP_ID ,IF(`Stop` like 'Load'  ,@stop_order:=1,@stop_order:=@stop_order +1) stop_order, Route, `Time`, `Stop` ,IF(`Stop` like 'IMU',1,0) MIDPOINT, case when `Stop` like 'Stadium ()' then @down:=1 when `Stop` like 'Load' then @down:=0 else @down end UP_DOWN from DBMAP_ScheduleData JOIN ( SELECT @row_num :=0)r JOIN ( SELECT @down :=0)x where Route like '%X2'  order by `ID`)fo4 left join  (SELECT STOP_ID,  case when STOP_NAME  like 'I M U (X)' then 'IMU'  when STOP_NAME  like 'Stadium (x)' then 'Stadium'  else STOP_NAME end STOP_NAME FROM S_Stop where STOP_NAME in ('I M U (X)' ,'Stadium (x)','Stadium ()'))s on  s.STOP_NAME = fo4.Stop