MATCH (a:Stops),(b:Stops) WHERE a.name = 'Fisher Court ()' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (x)' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann ()' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Alumni Center' AND b.name = 'Briscoe' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Neal Marshall' AND b.name = '3rd & Jordan' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'IMU' AND b.name = '10th & Woodlawn' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Briscoe ()' AND b.name = 'Assembly Hall ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Atwater Garage' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Lingelbach ()' AND b.name = 'Alumni Center' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Stadium (A)' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School' AND b.name = 'Well\'s Library' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Kirkwood & Indiana' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School ()' AND b.name = 'Foster' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Poplars Garage' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann Redbud' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library Jordan' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Briscoe' AND b.name = 'McNutt' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Jordan Hall' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th & Woodlawn' AND b.name = 'Psychology' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Assembly Hall ()' AND b.name = 'Stadium (A)' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium (X)' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = 'Alumni Center' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library' AND b.name = 'Neal Marshall' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kirkwood & Indiana' AND b.name = 'IMU' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Foster' AND b.name = 'Briscoe ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Campus View' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jackson Creek' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Walnut and Second' AND b.name = 'Stadium ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'SRSC ()' AND b.name = 'Alumni Center' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'McNutt' AND b.name = 'Kelley School' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Hall' AND b.name = 'Maurer School of Law' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Psychology' AND b.name = 'Kelley School ()' CREATE (a)-[r:A]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Briscoe' AND b.name = 'McNutt' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Jordan Hall' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th & Woodlawn' AND b.name = 'Psychology' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Assembly Hall ()' AND b.name = 'Stadium (A)' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = 'Alumni Center' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library' AND b.name = 'Neal Marshall' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kirkwood & Indiana' AND b.name = 'IMU' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Foster' AND b.name = 'Briscoe ()' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'McNutt' AND b.name = 'Kelley School' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Hall' AND b.name = 'Maurer School of Law' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Psychology' AND b.name = 'Kelley School ()' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Stadium (A)' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Alumni Center' AND b.name = 'Briscoe' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Neal Marshall' AND b.name = '3rd & Jordan' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'IMU' AND b.name = '10th & Woodlawn' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Briscoe ()' AND b.name = 'Assembly Hall ()' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School' AND b.name = 'Well\'s Library' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Kirkwood & Indiana' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School ()' AND b.name = 'Foster' CREATE (a)-[r:A Route M-R]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jackson Creek' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan & 7th' AND b.name = 'Lingelbach' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Jordan Hall' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Lingelbach ()' AND b.name = 'Phi Kappa Sigma ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann Redbud' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Balfour' AND b.name = 'Kappa Sigma' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann ()' AND b.name = 'Kappa Sigma' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th & Jordan' AND b.name = 'Neal Marshall' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th and Jordan ()' AND b.name = '10th & Jordan ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Balfour ()' AND b.name = 'ZBT ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Walnut and Second' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kirkwood & Indiana' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Fisher Court ()' AND b.name = 'ZBT' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Poplars Garage' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Lingelbach' AND b.name = 'Kappa Delta' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Hall' AND b.name = 'Maurer School of Law' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Phi Kappa Sigma ()' AND b.name = 'Chi Omega ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (x)' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Psychology' AND b.name = 'Kappa Delta' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Alumni Center' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kappa Sigma' AND b.name = 'Jordan & 7th' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Neal Marshall' AND b.name = '3rd & Jordan' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'SRSC ()' AND b.name = 'Lingelbach ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'ZBT()' AND b.name = 'ZBT ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Atwater Garage' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'ZBT' AND b.name = 'Balfour' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library' AND b.name = '3rd & Jordan' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kappa Delta' AND b.name = '10th & Jordan' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Garage' AND b.name = '10th & Jordan ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Chi Omega ()' AND b.name = 'Balfour ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Assembly Hall ()' AND b.name = 'ZBT' CREATE (a)-[r:B]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Atwater Garage' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann Redbud' AND b.name = 'Bicknell' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Union & 7th' AND b.name = 'Wilkie' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Kirkwood & Indiana' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library' AND b.name = 'School of Education' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Nutt Apartment ()' AND b.name = 'Nutt Apartments' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Fisher Court ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Poplars Garage' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'College Mall ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Campus View' AND b.name = 'Union & 10th' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Jordan Hall' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th & Woodlawn' AND b.name = 'Psychology' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Eigenmann' AND b.name = 'Campus View ()' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (x)' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Assembly Hall ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Bicknell' AND b.name = 'Hepburn Apartments' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Wilkie' AND b.name = 'Forest' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kirkwood & Indiana' AND b.name = 'IMU' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'School of Education' AND b.name = '7th & Union' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Bicknell ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Lingelbach ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jackson Creek' AND b.name = 'Forest' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '7th & Woodlawn' AND b.name = 'Union & 7th' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Union & 10th' AND b.name = 'Union & 7th' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Hall' AND b.name = 'Maurer School of Law' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Psychology' AND b.name = 'Well\'s Library' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Campus View ()' AND b.name = 'Nutt Apartments' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Alumni Center' AND b.name = 'Bicknell' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Foster' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Hepburn Apartment' AND b.name = 'Hepburn Apartments' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Forest' AND b.name = '3rd & Jordan' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'IMU' AND b.name = '10th & Woodlawn' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '7th & Union' AND b.name = 'Eigenmann' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan & 7th' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Fisher Court ()' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium (X)' AND b.name = 'Stadium (X)' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Walnut and Second' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Atwater Garage' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '7th & Woodlawn' AND b.name = 'IMU (X)' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jackson Creek' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Stadium (X)' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = '7th & Woodlawn' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann ()' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'I M U (X)' AND b.name = 'IMU (X)' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Poplars Garage' AND b.name = '7th & Woodlawn' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Neal Marshall' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (x)' AND b.name = '7th & Woodlawn' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann Redbud' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'College Mall ()' AND b.name = '7th & Woodlawn' CREATE (a)-[r:X]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Union & 10th' AND b.name = 'Stadium ()' CREATE (a)-[r:X]->(b);
