MATCH (a:Stops),(b:Stops) WHERE a.name = 'Walnut and Second' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 2618160.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = 'Alumni Center' CREATE (a)-[r:A { meantime : 5788.9400}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Briscoe' AND b.name = 'McNutt' CREATE (a)-[r:A { meantime : 52.2570}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School' AND b.name = 'Well\'s Library' CREATE (a)-[r:A { meantime : 152.5113}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Neal Marshall' AND b.name = '3rd & Jordan' CREATE (a)-[r:A { meantime : 115.7905}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Hall' AND b.name = 'Maurer School of Law' CREATE (a)-[r:A { meantime : 95.1564}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kirkwood & Indiana' AND b.name = 'IMU' CREATE (a)-[r:A { meantime : 116.1815}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th & Woodlawn' AND b.name = 'Psychology' CREATE (a)-[r:A { meantime : 75.9524}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School ()' AND b.name = 'Foster' CREATE (a)-[r:A { meantime : 66.0283}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Briscoe ()' AND b.name = 'Assembly Hall ()' CREATE (a)-[r:A { meantime : 73.9103}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Fisher Court ()' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 136782.2676}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Campus View' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 43137.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 94903.8889}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann Redbud' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 108014.1538}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Lingelbach ()' AND b.name = 'Alumni Center' CREATE (a)-[r:A { meantime : 68104.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann ()' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 158770.4000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'SRSC ()' AND b.name = 'Alumni Center' CREATE (a)-[r:A { meantime : 356.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Stadium (A)' CREATE (a)-[r:A { meantime : 2669.5765}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Alumni Center' AND b.name = 'Briscoe' CREATE (a)-[r:A { meantime : 99.8284}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'McNutt' AND b.name = 'Kelley School' CREATE (a)-[r:A { meantime : 66.2292}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library' AND b.name = 'Neal Marshall' CREATE (a)-[r:A { meantime : 171.3617}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Jordan Hall' CREATE (a)-[r:A { meantime : 81.2630}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Kirkwood & Indiana' CREATE (a)-[r:A { meantime : 264.1023}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'IMU' AND b.name = '10th & Woodlawn' CREATE (a)-[r:A { meantime : 147.4350}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Psychology' AND b.name = 'Kelley School ()' CREATE (a)-[r:A { meantime : 99.6091}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Foster' AND b.name = 'Briscoe ()' CREATE (a)-[r:A { meantime : 57.9496}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Assembly Hall ()' AND b.name = 'Stadium (A)' CREATE (a)-[r:A { meantime : 2462.2734}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Poplars Garage' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 35615.6000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Atwater Garage' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 64234.2000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (x)' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 101565.8000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jackson Creek' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 516669.6667}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium (x)' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 528.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Wells Library Jordan' AND b.name = 'Stadium ()' CREATE (a)-[r:A { meantime : 354105.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Alumni Center' AND b.name = 'Briscoe' CREATE (a)-[r:ARouteMR { meantime : 52.8750}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'McNutt' AND b.name = 'Kelley School' CREATE (a)-[r:ARouteMR { meantime : 50.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library' AND b.name = 'Neal Marshall' CREATE (a)-[r:ARouteMR { meantime : 98.2609}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Jordan Hall' CREATE (a)-[r:ARouteMR { meantime : 66.7826}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Kirkwood & Indiana' CREATE (a)-[r:ARouteMR { meantime : 52.5833}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'IMU' AND b.name = '10th & Woodlawn' CREATE (a)-[r:ARouteMR { meantime : 59.1250}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Psychology' AND b.name = 'Kelley School ()' CREATE (a)-[r:ARouteMR { meantime : 55.2800}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Foster' AND b.name = 'Briscoe ()' CREATE (a)-[r:ARouteMR { meantime : 44.8400}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Assembly Hall ()' AND b.name = 'Stadium (A)' CREATE (a)-[r:ARouteMR { meantime : 71.4400}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = 'Alumni Center' CREATE (a)-[r:ARouteMR { meantime : 1234.8696}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Briscoe' AND b.name = 'McNutt' CREATE (a)-[r:ARouteMR { meantime : 44.0435}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School' AND b.name = 'Well\'s Library' CREATE (a)-[r:ARouteMR { meantime : 71.2917}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Neal Marshall' AND b.name = '3rd & Jordan' CREATE (a)-[r:ARouteMR { meantime : 87.3478}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Hall' AND b.name = 'Maurer School of Law' CREATE (a)-[r:ARouteMR { meantime : 74.7500}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kirkwood & Indiana' AND b.name = 'IMU' CREATE (a)-[r:ARouteMR { meantime : 96.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th & Woodlawn' AND b.name = 'Psychology' CREATE (a)-[r:ARouteMR { meantime : 60.5200}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School ()' AND b.name = 'Foster' CREATE (a)-[r:ARouteMR { meantime : 48.4400}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Briscoe ()' AND b.name = 'Assembly Hall ()' CREATE (a)-[r:ARouteMR { meantime : 60.2800}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Stadium (A)' CREATE (a)-[r:ARouteMR { meantime : 653.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kappa Sigma' AND b.name = 'Jordan & 7th' CREATE (a)-[r:B { meantime : 59.0190}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Lingelbach' AND b.name = 'Kappa Delta' CREATE (a)-[r:B { meantime : 48.1591}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th & Jordan' AND b.name = 'Neal Marshall' CREATE (a)-[r:B { meantime : 169.8666}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Jordan Hall' CREATE (a)-[r:B { meantime : 74.5771}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Garage' AND b.name = '10th & Jordan ()' CREATE (a)-[r:B { meantime : 89.5738}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'SRSC ()' AND b.name = 'Lingelbach ()' CREATE (a)-[r:B { meantime : 45.4212}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Phi Kappa Sigma ()' AND b.name = 'Chi Omega ()' CREATE (a)-[r:B { meantime : 26.0554}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Balfour ()' AND b.name = 'ZBT ()' CREATE (a)-[r:B { meantime : 33.5988}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann Redbud' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 171396.6429}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 191754.5472}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Atwater Garage' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 153630.7778}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Psychology' AND b.name = 'Kappa Delta' CREATE (a)-[r:B { meantime : 211.5000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kirkwood & Indiana' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 4487155.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 66968.8000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jackson Creek' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 140465.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library' AND b.name = '3rd & Jordan' CREATE (a)-[r:B { meantime : 1378.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 413.5756}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'ZBT' AND b.name = 'Balfour' CREATE (a)-[r:B { meantime : 33.9218}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Balfour' AND b.name = 'Kappa Sigma' CREATE (a)-[r:B { meantime : 42.9886}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan & 7th' AND b.name = 'Lingelbach' CREATE (a)-[r:B { meantime : 145.2982}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kappa Delta' AND b.name = '10th & Jordan' CREATE (a)-[r:B { meantime : 55.9862}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Neal Marshall' AND b.name = '3rd & Jordan' CREATE (a)-[r:B { meantime : 110.3165}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Hall' AND b.name = 'Maurer School of Law' CREATE (a)-[r:B { meantime : 91.3648}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th and Jordan ()' AND b.name = '10th & Jordan ()' CREATE (a)-[r:B { meantime : 88.1951}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Lingelbach ()' AND b.name = 'Phi Kappa Sigma ()' CREATE (a)-[r:B { meantime : 89.0632}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Chi Omega ()' AND b.name = 'Balfour ()' CREATE (a)-[r:B { meantime : 39.8539}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'ZBT()' AND b.name = 'ZBT ()' CREATE (a)-[r:B { meantime : 25.6046}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (x)' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 89681.2353}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Walnut and Second' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 440319.6667}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 55033.7500}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Assembly Hall ()' AND b.name = 'ZBT' CREATE (a)-[r:B { meantime : 310151.2500}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 190835.5000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Alumni Center' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 245397.5000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Poplars Garage' AND b.name = 'Fisher Court ()' CREATE (a)-[r:B { meantime : 33460.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann ()' AND b.name = 'Kappa Sigma' CREATE (a)-[r:B { meantime : 402308.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Fisher Court ()' AND b.name = 'ZBT' CREATE (a)-[r:B { meantime : 6604.5002}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 154039.4000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Fisher Court ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 130427.8571}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Atwater Garage' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 162029.4000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 46415.8571}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jackson Creek' AND b.name = 'Forest' CREATE (a)-[r:E { meantime : 493661.3333}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Assembly Hall ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 102107.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'College Mall ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 500058.6667}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 128145.3548}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Bicknell' AND b.name = 'Hepburn Apartments' CREATE (a)-[r:E { meantime : 34.1157}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Campus View' AND b.name = 'Union & 10th' CREATE (a)-[r:E { meantime : 89.9663}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Union & 7th' AND b.name = 'Wilkie' CREATE (a)-[r:E { meantime : 61.9050}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Forest' AND b.name = '3rd & Jordan' CREATE (a)-[r:E { meantime : 99.9757}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan Hall' AND b.name = 'Maurer School of Law' CREATE (a)-[r:E { meantime : 92.5624}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kirkwood & Indiana' AND b.name = 'IMU' CREATE (a)-[r:E { meantime : 106.9543}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '10th & Woodlawn' AND b.name = 'Psychology' CREATE (a)-[r:E { meantime : 69.1825}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Well\'s Library' AND b.name = 'School of Education' CREATE (a)-[r:E { meantime : 148.9012}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '7th & Union' AND b.name = 'Eigenmann' CREATE (a)-[r:E { meantime : 48.9583}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Campus View ()' AND b.name = 'Nutt Apartments' CREATE (a)-[r:E { meantime : 51.3003}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Bicknell ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 47.8852}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Alumni Center' AND b.name = 'Bicknell' CREATE (a)-[r:E { meantime : 526.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Lingelbach ()' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 1244.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (x)' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 122074.7556}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Poplars Garage' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 42437.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 38143.5000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Foster' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 63846.5000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '7th & Woodlawn' AND b.name = 'Union & 7th' CREATE (a)-[r:E { meantime : 2244.5000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann Redbud' AND b.name = 'Bicknell' CREATE (a)-[r:E { meantime : 2806.8681}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Hepburn Apartment' AND b.name = 'Hepburn Apartments' CREATE (a)-[r:E { meantime : 39.5776}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Union & 10th' AND b.name = 'Union & 7th' CREATE (a)-[r:E { meantime : 57.5743}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Wilkie' AND b.name = 'Forest' CREATE (a)-[r:E { meantime : 98.2507}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Jordan Hall' CREATE (a)-[r:E { meantime : 74.2045}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Kirkwood & Indiana' CREATE (a)-[r:E { meantime : 458.1902}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'IMU' AND b.name = '10th & Woodlawn' CREATE (a)-[r:E { meantime : 169.7210}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Psychology' AND b.name = 'Well\'s Library' CREATE (a)-[r:E { meantime : 103.1934}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'School of Education' AND b.name = '7th & Union' CREATE (a)-[r:E { meantime : 44.1082}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Eigenmann' AND b.name = 'Campus View ()' CREATE (a)-[r:E { meantime : 90.0025}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Nutt Apartment ()' AND b.name = 'Nutt Apartments' CREATE (a)-[r:E { meantime : 30.5880}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jordan & 7th' AND b.name = 'Evermann Redbud' CREATE (a)-[r:E { meantime : 120505.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Fisher Court ()' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 108382.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (x)' AND b.name = '7th & Woodlawn' CREATE (a)-[r:X { meantime : 1323.2006}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'I M U (x)' AND b.name = 'IMU (x)' CREATE (a)-[r:X { meantime : 76.3857}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium (A)' AND b.name = '7th & Woodlawn' CREATE (a)-[r:X { meantime : 144193.6061}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Maurer School of Law' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 126587.7778}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Walnut and Second' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 352702.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'College Mall ()' AND b.name = '7th & Woodlawn' CREATE (a)-[r:X { meantime : 1950647.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Neal Marshall' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 161168.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann ()' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 110449.6667}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 201911.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Stadium ()' AND b.name = 'Stadium (x)' CREATE (a)-[r:X { meantime : 671.1283}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '7th & Woodlawn' AND b.name = 'IMU (x)' CREATE (a)-[r:X { meantime : 144.7906}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Auditorium (x)' AND b.name = 'Stadium (x)' CREATE (a)-[r:X { meantime : 379.1179}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Evermann Redbud' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 102286.9583}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Poplars Garage' AND b.name = '7th & Woodlawn' CREATE (a)-[r:X { meantime : 31982.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = '3rd & Jordan' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 1734.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Jackson Creek' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 438440.5000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Atwater Garage' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 74571.6667}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Union & 10th' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 94438.0000}]->(b);
MATCH (a:Stops),(b:Stops) WHERE a.name = 'Kelley School' AND b.name = 'Stadium ()' CREATE (a)-[r:X { meantime : 138211.0000}]->(b);
