create (a:Stops {name:'Well\'s Library'});
create (a:Stops {name:'Neal Marshall'});
create (a:Stops {name:'3rd & Jordan'});
create (a:Stops {name:'Jordan Hall'});
create (a:Stops {name:'Maurer School of Law'});
create (a:Stops {name:'Kirkwood & Indiana'});
create (a:Stops {name:'IMU'});
create (a:Stops {name:'10th & Woodlawn'});
create (a:Stops {name:'Psychology'});
create (a:Stops {name:'SRSC ()'});
create (a:Stops {name:'Phi Kappa Sigma ()'});
create (a:Stops {name:'Chi Omega ()'});
create (a:Stops {name:'Balfour ()'});
create (a:Stops {name:'ZBT()'});
create (a:Stops {name:'Fisher Court ()'});
create (a:Stops {name:'ZBT'});
create (a:Stops {name:'Balfour'});
create (a:Stops {name:'Kappa Sigma'});
create (a:Stops {name:'Jordan & 7th'});
create (a:Stops {name:'Lingelbach'});
create (a:Stops {name:'Foster'});
create (a:Stops {name:'Kappa Delta'});
create (a:Stops {name:'10th & Jordan'});
create (a:Stops {name:'Briscoe ()'});
create (a:Stops {name:'Assembly Hall ()'});
create (a:Stops {name:'Kelley School ()'});
create (a:Stops {name:'McNutt'});
create (a:Stops {name:'Briscoe'});
create (a:Stops {name:'Alumni Center'});
create (a:Stops {name:'Stadium (NA)'});
create (a:Stops {name:'Kelley School'});
create (a:Stops {name:'10th & Sunrise'});
create (a:Stops {name:'Wilkie'});
create (a:Stops {name:'Forest'});
create (a:Stops {name:'Evermann'});
create (a:Stops {name:'Bicknell'});
create (a:Stops {name:'Campus View'});
create (a:Stops {name:'Union & 10th'});
create (a:Stops {name:'Union & 7th'});
create (a:Stops {name:'School of Education'});
create (a:Stops {name:'7th & Union'});
create (a:Stops {name:'Eigenmann'});
create (a:Stops {name:'Campus View ()'});
create (a:Stops {name:'Hepburn Apartment'});
create (a:Stops {name:'Bicknell ()'});
create (a:Stops {name:'Evermann Redbud'});
create (a:Stops {name:'I M U (X)'});
create (a:Stops {name:'Auditorium'});
create (a:Stops {name:'Jackson Creek'});
create (a:Stops {name:'Stadium (A)'});
create (a:Stops {name:'Stadium ()'});
create (a:Stops {name:'Evermann ()'});
create (a:Stops {name:'Stadium Staging (NA)'});
create (a:Stops {name:'Lingelbach ()'});
create (a:Stops {name:'Stadium (x)'});
create (a:Stops {name:'Auditorium (X)'});
create (a:Stops {name:'Von Lee'});
create (a:Stops {name:'Nick\'s'});
create (a:Stops {name:'Kirkwood and Walnut'});
create (a:Stops {name:'7th & Washington'});
create (a:Stops {name:'Poplars Garage'});
create (a:Stops {name:'test 1 (NA)'});
create (a:Stops {name:'Jordan Garage'});
create (a:Stops {name:'10th and Jordan ()'});
create (a:Stops {name:'College Mall ()'});
create (a:Stops {name:'College Mall'});
create (a:Stops {name:'Atwater Garage'});
create (a:Stops {name:'Fisher Court'});
create (a:Stops {name:'Bonefish Grill (NA)'});
create (a:Stops {name:'Marsh (NA)'});
create (a:Stops {name:'Inbound A, Library Detour (NA)'});
create (a:Stops {name:'7th and Sunrise'});
create (a:Stops {name:'Tulip Tree Apartments (NA)'});
create (a:Stops {name:'10th and Jordan, Tulip Tree Detour (Inbound) (NA)'});
create (a:Stops {name:'College Mall End (NA)'});
create (a:Stops {name:'Nutt Apartment ()'});
create (a:Stops {name:'Poplars'});
create (a:Stops {name:'DoubleMap Visibility Test'});
create (a:Stops {name:'Chi Omega'});
create (a:Stops {name:'17th and Fee'});
create (a:Stops {name:'Jordan and Law Lane'});
create (a:Stops {name:'Wells Library Jordan'});
create (a:Stops {name:'19th and Dunn'});
create (a:Stops {name:'McNutt Turnaround'});
create (a:Stops {name:'Memorial Hall'});
create (a:Stops {name:'7th and Jordan'});
create (a:Stops {name:'7th & Woodlawn'});
create (a:Stops {name:'Walnut and First'});
create (a:Stops {name:'Bus Barn'});
create (a:Stops {name:'Walnut and Second'});
create (a:Stops {name:'Second and College'});
create (a:Stops {name:'College and First'});
create (a:Stops {name:'test kyle'});
create (a:Stops {name:'Orange Lot'});
create (a:Stops {name:'Rawles Hall'});
create (a:Stops {name:'IU Foundation'});
create (a:Stops {name:'Mathers Museum'});
create (a:Stops {name:'Kelley School - Law Ln Detour'});
